name: build

on:
  workflow_dispatch:
  push:
    branches: [ '1.19.2' ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: build
        run: |
          git clone https://github.com/perkinslr/oc2r/
          cd oc2r
          git checkout 1.18.x
          mkdir libs
          wget https://github.com/perkinslr/oc2r/releases/latest/download/sedna.jar -O libs/sedna.jar
          ./gradlew build
          git checkout 1.20.1
          ./gradlew build
          git checkout 1.19.2
          wget https://proxy-maven.covers1624.net/repository/maven-public/mrtjp/ProjectRed/1.19.2-4.19.0-beta%2B33/ProjectRed-1.19.2-4.19.0-beta%2B33-api.jar -O libs/ProjectRed.jar
          ./gradlew build
