name: publish

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: build
        run: |
          wget https://raw.githubusercontent.com/perkinslr/buildroot-sedna/refs/heads/main/build.sh
          bash build.sh
      
        
      - name: Update Manifest
        run: |
          cat oc2r/gradle.properties  | grep semver >> $GITHUB_ENV

      - name: Create Version Release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.semver }}
          allowUpdates: false
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "oc2r/build/libs/*.jar,sedna.jar"
          tag: ${{ env.semver }}
